# Config file for automatic testing at travis-ci.org

language: python
python: 3.5

env:
  - TOXENV=py35
  - TOXENV=py27
  - TOXENV=py26
  - TOXENV=pypy

install: pip install -U tox

script: tox -e ${TOXENV}
